// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqKSE2Fq5gQMpCKOyLzYZE1lkRiPVKdV0',
    appId: '1:716210582245:web:549a950c1a2bd238061a0c',
    messagingSenderId: '716210582245',
    projectId: 'mercadopoupanca-2aac2',
    authDomain: 'mercadopoupanca-2aac2.firebaseapp.com',
    storageBucket: 'mercadopoupanca-2aac2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbhDYDcTbLyU6J7y2qr5p3qdvMfQLjzqo',
    appId: '1:716210582245:android:0879247f89f580a4061a0c',
    messagingSenderId: '716210582245',
    projectId: 'mercadopoupanca-2aac2',
    storageBucket: 'mercadopoupanca-2aac2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDYrYz2IKvBOz82ssHajXDQFOvCikF2dI',
    appId: '1:716210582245:ios:133684bf1c27d8df061a0c',
    messagingSenderId: '716210582245',
    projectId: 'mercadopoupanca-2aac2',
    storageBucket: 'mercadopoupanca-2aac2.appspot.com',
    iosBundleId: 'com.example.mercadopoupanca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDYrYz2IKvBOz82ssHajXDQFOvCikF2dI',
    appId: '1:716210582245:ios:1f05102b783f7ece061a0c',
    messagingSenderId: '716210582245',
    projectId: 'mercadopoupanca-2aac2',
    storageBucket: 'mercadopoupanca-2aac2.appspot.com',
    iosBundleId: 'com.example.mercadopoupanca.RunnerTests',
  );
}
